# Generated by Django 3.0.1 on 2020-01-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sale1'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpr_cust_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_code', models.CharField(max_length=100)),
                ('cust_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dprCumulative_cellLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('today_quantityCell', models.CharField(max_length=100)),
                ('cumulative_quantityCell', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dprExcel_cellLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longTerm_bulkerNo', models.CharField(max_length=100)),
                ('longTerm_quantity', models.CharField(max_length=100)),
                ('shortTerm_bulkerNo', models.CharField(max_length=100)),
                ('shortTerm_quantity', models.CharField(max_length=100)),
                ('brick_bulkerNo', models.CharField(max_length=100)),
                ('brick_quantity', models.CharField(max_length=100)),
            ],
        ),
    ]
