# Generated by Django 3.0.1 on 2020-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dpr_cust_code_dprcumulative_celllocation_dprexcel_celllocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpr_cust_code_shortTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_code', models.CharField(max_length=100)),
                ('cust_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dpr_cust_codeFoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_code', models.CharField(max_length=100)),
                ('cust_name', models.CharField(max_length=100)),
            ],
        ),
    ]
