# Generated by Django 3.0.1 on 2020-02-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dpr_cust_code_shortterm_dpr_cust_codefoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel_sheet_path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_report', models.CharField(max_length=100)),
                ('sale_detail', models.CharField(max_length=100)),
                ('ash_utilization', models.CharField(max_length=100)),
            ],
        ),
    ]
